name: AWS CLI test workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  checkout-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout current repo using hv-checkout
        uses: hv-actions/checkout@master

      - name: testing checkout
        run: |
          ls -a
          ls -ltr ./aws-cli-action

      # - name: AWS CLI Action
      #   uses: ./
      #   with:
      #     command: --version