name: AWS CLI test workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:

  checkout-tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout current repo using checkout
        uses: actions/checkout@v2

      - name: testing checkout
        run: |
          ls -ltr

      - name: AWS CLI Action
        uses: ./aws-cli-action
        with:
          command: --version